services:
  mongo-db:
    image: mongo:6.0.6
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      TZ: America/Santiago
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-test:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Santiago
      PGTZ: America/Santiago
    ports:
      - "5432:5432"
    volumes:
      - postgres-test:/var/lib/postgresql/data
      # Si quieres scripts de inicialización (SQL/SH):
      # - ./postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  mongo-test:
  postgres-test: